services:
  redis:
    image: "redis:7"
    container_name: "redis"
    ports:
      - "6379:6379"

  dispatcher:
    container_name: "dispatcher"
    build:
      context: packages/dispatcher
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      RANDOM_DISPATCH: "${RANDOM_DISPATCH:-false}"
    depends_on:
      - redis
    ports:
      - "8080:8080"

  log-handler:
    container_name: "log-handler"
    build:
      context: packages/log-collector
    environment:
      LOG_FILE: "${LOG_FILE:-/app/logs/collector.log}"
    ports:
      - "8001:8001"
    volumes:
      - "./logs:/app/logs"

  worker:
    build:
      context: packages/worker
    environment:
      WORKER_REDIS_HOST: "redis"
      LOG_COLLECTOR_ENABLED: "true"
      LOG_COLLECTOR_HOST: "http://log-handler:8001"
      LOG_COLLECTOR_LEVEL: "INFO"
    depends_on:
      - redis
      - log-handler
