version: 3
tasks:
  test-worker:
    desc: Run unit tests for the worker code.
    dir: packages/worker
    cmd: uv run pytest {{.CLI_ARGS}}

  test-dispatcher:
    desc: Run unit tests for the dispatcher code.
    dir: packages/dispatcher/dispatcher
    cmd: go test

  unit-tests:
    desc: Run unit tests for all components.
    cmds:
      - task: test-worker
      - task: test-dispatcher

  start:
    desc: Start the services (dispatcher, log-handler, worker, and redis)
    cmd: docker compose up -d --build {{.CLI_ARGS}}

  stop:
    desc: Stop the services
    cmd: docker compose down --rmi local

  build-producer:
    desc: Build the produce binary for benchmarking / testing.
    dir: packages/producer/producer
    sources:
      - "*.go"
      - "go.mod"
    cmd: (test -d ../../../bin || mkdir ../../../bin) && rm -f ../../../bin/producer && go build -o ../../../bin/producer
