version: 3
tasks:
  test-worker:
    desc: Run unit tests for the worker code.
    dir: packages/worker
    cmd: uv run pytest {{.CLI_ARGS}}

  test-dispatcher:
    desc: Run unit tests for the dispatcher code.
    dir: packages/dispatcher/dispatcher
    cmd: go test

  test-log-parsing:
    desc: Run unit tests for the log parsing code.
    dir: packages/benchmark/log-parse
    cmd: go test

  unit-tests:
    desc: Run unit tests for all components.
    cmds:
      - task: test-worker
      - task: test-dispatcher
      - task: test-log-parsing

  start-docker:
    desc: Start the docker services (dispatcher, log-handler, worker, and redis)
    cmd: docker compose up -d --build --scale "worker={{.NUM_WORKERS}}"
    env:
      LOG_FILE: "/app/logs/{{.RUN_ID}}/collector.log"
    requires:
      vars:
        - "RUN_ID"
        - "NUM_WORKERS"

  start:
    desc: Start the services (dispatcher, log-handler, worker, and redis)
    cmds:
      - task: start-docker
        vars:
          NUM_WORKERS: 1
          RUN_ID:
            sh: date "+%Y-%m-%d-%H%M"

  stop:
    desc: Stop the services
    cmd: docker compose down --rmi local

  build-producer:
    desc: Build the produce binary for benchmarking / testing.
    dir: packages/benchmark/benchmark
    sources:
      - "*.go"
      - "go.mod"
    cmds:
      - (test -d ../../../bin || mkdir ../../../bin)
      - rm -f ../../../bin/benchmark
      - go build -o ../../../bin/benchmark

  build-log-processor:
    desc: Build the produce binary for benchmarking / testing.
    dir: packages/benchmark/log-parse
    sources:
      - "*.go"
      - "go.mod"
    cmds:
      - (test -d ../../../bin || mkdir ../../../bin)
      - rm -f ../../../bin/log-parse
      - go build -o ../../../bin/log-parse

  run-benchmark:
    desc: Start the services and run the producer to benchmark the system.
    vars:
      RUN_ID:
        sh: date "+%Y-%m-%d-%H%M"
      PRODUCER_LOG_FILE: "./logs/{{.RUN_ID}}/producer.log"
    cmds:
      - mkdir -p ./logs/{{.RUN_ID}}
      - task: start-docker
        vars:
          RUN_ID: "{{.RUN_ID}}"
          NUM_WORKERS: "{{.NUM_WORKERS}}"

      - task: build-producer
      - task: build-log-processor

      # Give some time for startup
      - sleep 10

      # Run the producer - fix the log file and settings file for easy reference
      - |
        DISPATCHER_URL=http://localhost:8080 \
                      ./bin/producer \
                        --log-file={{.PRODUCER_LOG_FILE}} \
                        --settings=./logs/{{.RUN_ID}}/settings.json \
                        {{.CLI_ARGS}}

      # Give some time for pending tasks to complete
      - sleep 60

      - task: stop
