[project]
name = "worker"
version = "0.0.1"
description = "Worker for smart routing"
requires-python = ">=3.13,<3.14"
dependencies = [
    "pydantic>=2,<3",
    "pydantic-settings>=2,<3",
    "redis>=6.4.0,<7",
]
