[project]
name = "worker"
version = "0.0.1"
description = "Worker for smart routing"
requires-python = ">=3.13,<3.14"
dependencies = [
    "loguru>=0.7.3,<0.8",
    "pydantic>=2,<3",
    "pydantic-settings>=2,<3",
    "redis>=6.4.0,<7",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
pythonpath = [
    "src",
]
markers = [
    "live_redis: Mark test to run only with a live Redis server running locally",
]

[dependency-groups]
dev = [
    "fakeredis>=2.31.0",
]
